resources:
- grafana-config.yaml
- grafana-dashboardDatasources.yaml
- grafana-dashboardDefinitions.yaml
- grafana-dashboardSources.yaml
- grafana-deployment.yaml
- grafana-service.yaml
- grafana-serviceAccount.yaml
- grafana-serviceMonitor.yaml
- grafana-storage.yaml

